### PR TITLE
Equip armour

### PR DESCRIPTION
**Pull request by paddatrapper**
Fixes bugs when equipping armour. It also updates the test profile to be in line with recent changes

### CODE REVIEW

**Comment by projectdelphai** [comment]
This commit works but breaks equipping food. Trying to eat food adds +0 to health.

**Comment by paddatrapper** [comment]
Fixed

**Comment by projectdelphai** [comment]
works well except equipping leather gauntlets still doesn't work

**Comment by paddatrapper** [comment]
Armour values are adjusted, however it is not added to the equipment list correct? If so I'm working on it at the moment

**Comment by projectdelphai** [comment]
yep, that's what's happening. it's strangely specific to leather gauntlets though

**Comment by paddatrapper** [comment]
It's similar to the issue with equipping two handed weapons - gauntlets are armour for both arms

**Comment by paddatrapper** [comment]
Fixed

**Pull request merged**
