### PR TITLE
20150726First

### PR DESCRIPTION
**Pull request by 798740023**
第一次使用，学习Java

### CODE REVIEW

**Comment by projectdelphai** [comment]
um what? first, can you translate that into english for me? and a brief description of what this commit is about along with a more recognizable title. I'm giving you the benefit of the doubt that you're actually trying to contribute but a lot of factors seem to point to the fact that this is spam or a troll pull request. Please convince me otherwise because it'd be great to have some contributions. I'll give you a couple of days and then close this pull request if nothing changes.

**Comment by paddatrapper** [comment]
Seems to me like it is simply what has already been done

**Comment by projectdelphai** [comment]
yeah just wondering about the new comment though

**Comment by paddatrapper** [comment]
Yeah. That isn't rendering at all for me. Definitely looks like a spam PR

**Comment by projectdelphai** [comment]
pretty sure it's chinese. i have a friend who can translate so i'll ask when she comes on. if it isn't useful, i'll close this. and then maybe merge all these commits later if i have time lol. and i can remember what they all do

**Comment by paddatrapper** [comment]
These commits shouldn't be merged into gh-pages... gh-pages branch is the github.io site

**Comment by projectdelphai** [comment]
yeah, agreed. thought these were some other commits but it's literally just merging master into gh-pages. *smh* closed

**Pull request closed without merging**
