### PR TITLE
Ant Ivy - Issue #157

### PR DESCRIPTION
**Pull request by paddatrapper**
Adds ant ivy use to resolve and download dependencies as suggested by issue #157. This requires ivy to be downloaded and installed from [Apache](http://ant.apache.org/ivy/download.cgi) and installed. Tutorials on how to do this are available [here](http://ant.apache.org/ivy/history/latest-milestone/tutorial.html).

### CODE REVIEW

**Comment by verhagen** [comment]
@paddatrapper Please read the update on #157 Which hopefully makes it more clear why and how to use ivy, for the libraries (jars).

**Comment by paddatrapper** [comment]
Yeah I realised while I was messing with it yesterday. Thanks

**Comment by paddatrapper** [comment]
Does someone mind merging or rejecting these pull requests? I am reluctant to work on other issues until these have been finalised.

**Comment by projectdelphai** [comment]
hey sorry, i'm pretty sick right now and can't really help out for a while. maybe @verhagen?

**Comment by paddatrapper** [comment]
No worries. Get better soon

**Comment by projectdelphai** [comment]
okay so looking through this and it works pretty well. The only issue was that I had 2.3 installed so i had to change the version number in ivy.xml to 2.3 from 2.4 and it started working again. merging then.

**Pull request merged**
