### PR TITLE
Add packaging command and start work on fixing 221

### PR DESCRIPTION
**Pull request by Dev-Osmium**

### CODE REVIEW

**Comment by paddatrapper** [comment]
I think a better way of approaching packaging is to do it in a platform agnostic way such as is suggested [here](https://stackoverflow.com/questions/33643599/create-zip-in-maven-with-additional-files-next-to-the-jar)

**Comment by Dev-Osmium** [comment]
I mean, right now this works. We should probably do something like that in the future.

**Comment by Dev-Osmium** [comment]
I mean, right now this works. We should probably do something like that in the future.

**Comment by Dev-Osmium** [comment]
@paddatrapper That should do it. Run `mvn assembly:single` after packaging the new JAR to create a zip, a tar.gz, and a tar.bz2

**Comment by Dev-Osmium** [comment]
Just fixed that, it no longer includes the lib files in the compressed archive as separate jars.

**Comment by Dev-Osmium** [comment]
I'm not seeing that error at all in any of my files

**Comment by Dev-Osmium** [comment]
Oh I see why, the json folder isn't being included in the tar.gz

**Comment by paddatrapper** [comment]
It is being included: 
```
tar -xvf target/jadventure-0.4-SNAPSHOT-bin.tar.gz 
jadventure-0.4-SNAPSHOT/jadventure-0.4-SNAPSHOT.jar
jadventure-0.4-SNAPSHOT/original-jadventure-0.4-SNAPSHOT.jar
jadventure-0.4-SNAPSHOT/json/locations.json
jadventure-0.4-SNAPSHOT/json/original_data/items.json
jadventure-0.4-SNAPSHOT/json/original_data/npcs.json
jadventure-0.4-SNAPSHOT/json/original_data/character_transitions.json
jadventure-0.4-SNAPSHOT/json/original_data/locations.json
```

**Comment by paddatrapper** [comment]
It is missing `json/profiles`, which is why load is failing. This should be created in the code when loading or a better error message displayed

**Pull request merged**
