### PR TITLE
Clearly explain how to run the program

### PR DESCRIPTION
**Pull request by PillarsZhang**
Clearly explain how to run the program.
Help those who use Maven for the first time (Like me...Be able neither to cry nor to laugh...)
I have spent 2 hours to figure out it...
run `mvn compile` & `mvn exec:java` to play the game

### CODE REVIEW

**Comment by PillarsZhang** [comment]
I mean running directly from source without importing into the IDE
I am not very familiar with these...

**Comment by Dev-Osmium** [comment]
I wrote a packaging PS script that builds a jar and packages the json/ folder into a .ZIP. We can start distributing this instead of making people install external tools

**Comment by paddatrapper** [comment]
What errors were you running into when not running mvn compile first?

**Comment by Dev-Osmium** [comment]
Can you run that again with the -e argument?

**Comment by paddatrapper** [comment]
I get the same error. `mvn compile` is needed before running the game.

**Comment by PillarsZhang** [comment]
@Dev-Osmium 
The same problem, summed up is `java.lang.ClassNotFoundException`
_I found this information:_
> Compile the code before running, exec:java will not automatically compile the code, you need to manually execute mvn compile to complete the compilation.

**Pull request merged**
